FROM node:20 as install_dependencies
WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts

FROM node:20 as start
WORKDIR /app
COPY src/ ./src/
COPY .env.local ./
COPY package.json ./
COPY tsconfig.json ./
COPY config/ ./config/
COPY --from=install_dependencies /app/node_modules ./node_modules
EXPOSE 3000
CMD ["npm", "run", "start:dev"]
