version: '3.8'

x-web-template: &web-template
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
    - .:/app
    - /app/node_modules
  expose:
    - '3000'
  env_file:
    - .env.local
    - src/infrastructure/database/prisma/.env
  depends_on:
    postgres:
      condition: service_healthy
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: '1GB'

services:
  web1:
    <<: *web-template
    hostname: web1

  web2:
    <<: *web-template
    hostname: web2

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_password
      - POSTGRES_DB=nestjs_full_architecture
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U local_user -d nestjs_full_architecture'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'

  nginx:
    image: nginx:latest
    ports:
      - '9999:9999'
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'

volumes:
  postgres_data:
