FROM node:20 AS development
WORKDIR /app
COPY .env ./
COPY src/ ./src/
COPY package*.json ./
COPY tsconfig.json ./
COPY config/ ./config/
RUN npm ci --ignore-scripts
EXPOSE 3000
CMD ["npm", "run", "start:dev"]