FROM node:20
WORKDIR /app
COPY src/ ./src/
COPY .env.local ./
COPY package*.json ./
COPY tsconfig.json ./
COPY config/ ./config/
RUN npm ci --omit-dev --ignore-scripts
EXPOSE 3000
CMD ["npm", "run", "start:dev"]