FROM node:20 as install_dependencies
WORKDIR /app
COPY package*.json ./
RUN npm ci --ignore-scripts

FROM node:20 as start
WORKDIR /app
COPY src/ ./src/
COPY package.json ./
COPY tsconfig.json ./
COPY jest-e2e.config.json ./
COPY __mocks__/ ./__mocks__/
COPY __tests__/e2e/ ./__tests__/e2e/
COPY --from=install_dependencies /app/node_modules ./node_modules
CMD ["npm", "run", "test:e2e:dev"]

