version: '3.8'

x-web-environment: &web-environment
  NODE_ENV: local
  HTTP_PORT: 3000
  POSTGRES_HOST: postgres
  POSTGRES_USER: local_user
  POSTGRES_PASSWORD: local_password
  JWT_SECRET: mysecretsecret

x-web-template: &web-template
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
    - .:/app
    - /app/node_modules
  expose:
    - '3000'
  env_file:
    - prisma/.env
  environment:
    <<: *web-environment
  depends_on:
    - postgres
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: '1GB'

services:
  web1:
    <<: *web-template
    hostname: web1

  web2:
    <<: *web-template
    hostname: web2

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=nestjs_full_architecture
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'

  nginx:
    image: nginx:latest
    ports:
      - '9999:9999'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'

volumes:
  postgres_data:
