version: '3.8'

services:
  app-e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e.dev
    volumes:
      - .:/app
    environment:
      NODE_ENV: local
      HTTP_PORT: 3000
      POSTGRES_HOST: postgres
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      JWT_SECRET: mysecretsecret
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=nestjs_full_architecture
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'

volumes:
  postgres_data:
